version: '3.1'
services:
  db:
    container_name: postgres-hacktiv
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go_api_jwt
    ports:
      - "5432:5432"